import json

EE = {
1: "He allowed me to come in here.",
2: "She attends the weekly meetings.",
3: "I strongly recommend this restaurant.",
4: "It is hard to express your feelings in words.",
5: "It is important to create new ideas.",
6: "Let's take action to protect the environment.",
7: "This price includes tax.",
8: "Temperatures have been rising every year.",
9: "I decided to go to university.",
10: "The teacher explained the problem in an easy-to-understand way.",
11: "Scientists discovered a new planet.",
12: "I worked hard to achieve my goal.",
13: "Let's think of a way to solve this problem.",
14: "I suggest a different method.",
15: "I want to improve my English skills.",
16: "I received a present from my friend.",
17: "I need to prepare for the exam.",
18: "Let's not forget her birthday.",
19: "I continued practicing even in the rain.",
20: "I practice the piano every day.",
21: "I offered to help.",
22: "The earthquake caused a lot of damage.",
23: "We all celebrated his birthday together.",
24: "We need to try to reduce the amount of garbage.",
25: "I supported my friend.",
26: "We are developing new technology.",
27: "The school provided teaching materials for us.",
28: "This part-time job requires experience.",
29: "I tried many times and finally succeeded.",
30: "Reading has a big influence on your life.",
31: "My hobby is collecting stamps.",
32: "I'm expecting good results.",
33: "Believe in your own possibilities.",
34: "I realized I had made a mistake.",
35: "I was introduced to a new friend.",
36: "We announced the new plan.",
37: "They delivered the package to me.",
38: "I want to travel abroad next year.",
39: "This factory produces cars.",
40: "Don't be afraid of failure — keep trying.",
41: "It is important to protect the global environment.",
42: "The government made a new law.",
43: "I took part in volunteer activities in the community.",
44: "Education is important for the future.",
45: "The latest technology is changing our lives.",
46: "My experience abroad was very useful.",
47: "I looked up information on the Internet.",
48: "Don't miss a good opportunity.",
49: "Japan's population is decreasing.",
50: "The TV commercial caught my attention.",
51: "I made a reservation at the restaurant.",
52: "I took medicine for my cold.",
53: "The concert performance was wonderful.",
54: "I want to gain a wide range of knowledge.",
55: "I faced a difficult situation.",
56: "I enjoy extracurricular activities at school.",
57: "I really like the atmosphere of that café.",
58: "Let's pay attention to the teacher's words.",
59: "A positive attitude is important.",
60: "The exam results were announced.",
61: "Health is the most important thing.",
62: "I am interested in Japanese culture.",
63: "Let's think about problems in society.",
64: "We conducted research on the environment.",
65: "Renewable energy is getting a lot of attention.",
66: "Environmental problems are serious.",
67: "What is the purpose of your trip?",
68: "I explained the reason I was late.",
69: "My favorite subject is English.",
70: "The service at this hotel is wonderful.",
71: "We launched a new product.",
72: "I participated in a local event.",
73: "I am studying Japanese history.",
74: "The 21st century is the age of information.",
75: "If you make an effort, your dreams will come true.",
76: "Let's try new challenges.",
77: "It is important to have the ability to make your own choices.",
78: "This medicine worked quickly.",
79: "Let's develop good habits.",
80: "I have a strong interest in music.",
81: "Environmental issues are an important challenge.",
82: "We use eco-friendly materials.",
83: "Let's find an effective study method.",
84: "I refreshed myself in nature.",
85: "I made a travel plan.",
86: "I submitted a research report.",
87: "We confirmed each person's role.",
88: "Let's improve our communication skills.",
89: "We are working on it as a group.",
90: "Science is advancing day by day.",
91: "This product is available right now.",
92: "I like traditional Japanese culture.",
93: "He is a successful businessman.",
94: "A house near the station is convenient.",
95: "Health is the most important thing.",
96: "It is dangerous to walk alone at night.",
97: "Her grades are excellent.",
98: "This sofa is very comfortable to sit on.",
99: "I was able to give the presentation with confidence.",
100: "This song is very popular.",
101: "A cold is a common illness in winter.",
102: "The two opinions are similar.",
103: "Let's check recent news.",
104: "I heard various opinions.",
105: "Studying English will be necessary in the future.",
106: "Believe that anything is possible.",
107: "I like modern design.",
108: "Global warming is a worldwide problem.",
109: "This is a serious problem.",
110: "She is a person with independent thinking.",
111: "I especially like sports.",
112: "Actually, I'm good at English.",
113: "My dream finally came true.",
114: "I recently read a new book.",
115: "He is probably right.",
116: "However, the situation has changed.",
117: "Therefore, this method is the best.",
118: "Unfortunately, I failed the exam.",
119: "That is exactly what I want to say.",
120: "That is certainly correct.",
121: "It is important to admit your mistakes.",
122: "I can't afford to buy this car.",
123: "I appreciate your help.",
124: "The storm destroyed the house.",
125: "Let's wash our hands to prevent illness.",
126: "I published a novel.",
127: "I could recognize my friend's face from far away.",
128: "I wonder if aliens exist.",
129: "We compete against athletes from around the world.",
130: "Success depends on your effort.",
131: "I managed to handle it on my own.",
132: "I completed the task.",
133: "We connected the two places.",
134: "I considered various opinions.",
135: "I will contact you later.",
136: "I want to contribute to society.",
137: "We cooperated as a team to do the work.",
138: "We discussed environmental issues.",
139: "I encouraged my friend.",
140: "It is important to maintain your health.",
141: "I obtained the necessary information.",
142: "I operate the machine well.",
143: "I participated in the debate.",
144: "I performed on stage.",
145: "I recycle plastic bottles.",
146: "I refused the invitation.",
147: "I rely on my family.",
148: "I replaced the old one with a new one.",
149: "I responded right away.",
150: "I selected the best one.",
151: "Let's share information.",
152: "I struggled to overcome the difficulty.",
153: "We trade with foreign countries.",
154: "I translated English into Japanese.",
155: "I warned them of the danger.",
156: "I borrowed a book from my friend.",
157: "I canceled the reservation.",
158: "The typhoon damaged the building.",
159: "I designed the website.",
160: "I gained a lot of experience.",
161: "I will graduate from university next spring.",
162: "I invited them to the birthday party.",
163: "I injured my leg during the game.",
164: "Don't waste your time.",
165: "I evaluate my own abilities.",
166: "It is important to be prepared for natural disasters.",
167: "I was involved in a traffic accident.",
168: "Polite behavior is important.",
169: "The audience gave a big round of applause.",
170: "We have sports equipment ready.",
171: "Music has an influence on people's hearts.",
172: "Let's prepare now for the future.",
173: "It is important to learn from mistakes.",
174: "Believe in your own ability.",
175: "It is a 15-minute walk to school.",
176: "They told me the direction.",
177: "Exercise has many benefits for your health.",
178: "Let's contribute to society as good citizens.",
179: "I entered an English speech contest.",
180: "I checked the weather conditions.",
181: "I practiced having a conversation in English.",
182: "Don't take unnecessary risks.",
183: "Technology is developing rapidly.",
184: "I overcame the difficulty.",
185: "I consulted a medical expert.",
186: "Let's sort and throw away garbage.",
187: "The tourism industry is developing.",
188: "It is fun to learn a foreign language.",
189: "We put safety measures in place.",
190: "Many nations are cooperating.",
191: "I get along well with the neighbors.",
192: "Patience is the key to success.",
193: "The Earth is a beautiful planet.",
194: "Air pollution is a serious problem.",
195: "I am making steady progress.",
196: "We make high-quality products.",
197: "Let's be careful about traffic safety.",
198: "I thought of a solution to the problem.",
199: "Let's use reliable sources.",
200: "I worked hard to succeed.",
201: "We introduced a new system.",
202: "Today's topic is environmental issues.",
203: "I want to preserve Japanese traditions.",
204: "Let's use public transportation.",
205: "I participated in local volunteer activities.",
206: "Let's stop wasting food.",
207: "We work to improve social welfare.",
208: "Tourism supports the local economy.",
209: "The number of tourists from abroad has increased.",
210: "There are many passengers on the crowded train.",
211: "I checked the weather forecast.",
212: "There is a discount at the sale.",
213: "The invention of the telephone changed our lives.",
214: "We are making efforts to prevent crime.",
215: "Let's have the courage to try.",
216: "Let's go on a new adventure.",
217: "Both sides reached an agreement.",
218: "Let's start with a small amount.",
219: "I read an English article.",
220: "I attended the graduation ceremony.",
221: "I donated to a charity.",
222: "I spent time in a comfortable environment.",
223: "The younger generation will change society.",
224: "It is important to give a good image.",
225: "Let's use natural resources carefully.",
226: "I studied the history of ancient Rome.",
227: "I am aware of the importance of the problem.",
228: "It is a central place near the station.",
229: "Colorful paintings are displayed.",
230: "The morning train is very crowded.",
231: "I was disappointed to lose the game.",
232: "I'm exhausted after working all day.",
233: "Fair rules are necessary.",
234: "I was amazed by the huge building.",
235: "It looks like it will rain.",
236: "It is most comfortable to speak in your native language.",
237: "I was very nervous before the presentation.",
238: "I checked the information on the official website.",
239: "It is important to build up your physical strength.",
240: "Let's take responsibility for our own actions.",
241: "A typical Japanese breakfast.",
242: "I have a unique idea.",
243: "The pace of urban life is fast.",
244: "I had a valuable experience.",
245: "The whole class participated.",
246: "I want to study abroad next year.",
247: "We moved the plan ahead of schedule.",
248: "It is also fun to travel alone.",
249: "Anyway, it is important not to give up.",
250: "This problem is easy to solve.",
251: "Even a child can solve this problem.",
252: "I can see the scenery far away.",
253: "I took the train instead of the bus.",
254: "I have been reading a lot lately.",
255: "Luckily, I made it to the train on time.",
256: "There is a convenience store nearby.",
257: "I like exercising outdoors.",
258: "Emergencies should be handled immediately.",
259: "We are nearly at the end.",
260: "Technology is constantly advancing.",
261: "I was bitten by a dog.",
262: "I folded the paper and put it in an envelope.",
263: "I confirmed the reservation.",
264: "I denied the accusation.",
265: "I treated my friend to a meal.",
266: "My wallet was stolen.",
267: "I hid during the game of hide-and-seek.",
268: "The colors of the clothes match.",
269: "I painted the wall.",
270: "He seems to be tired.",
271: "I fed the cat.",
272: "I described the situation in detail.",
273: "I wondered if he would come.",
274: "I fixed the broken bicycle.",
275: "I threw the ball far.",
276: "I pulled the door to open it.",
277: "I covered my body with a blanket.",
278: "I pushed the button.",
279: "I served the food at the table.",
280: "A school event was held.",
281: "I followed the teacher's instructions.",
282: "I joined the club.",
283: "I planted flowers in the garden.",
284: "I relaxed on my day off.",
285: "I ordered a meal at the restaurant.",
286: "We had a surprise party for his birthday.",
287: "I plan to get married next year.",
288: "We adopted a new rule.",
289: "We hired a part-time worker.",
290: "I limited the usage time.",
291: "I mixed the ingredients.",
292: "I organized the event.",
293: "I repaired the broken machine.",
294: "I returned the book to the library.",
295: "Let's save electricity to protect the environment.",
296: "I won the game.",
297: "I accepted the proposal.",
298: "I applied to the university.",
299: "Let's avoid trouble.",
300: "I built a new house.",
301: "The bread from the neighborhood bakery is delicious.",
302: "I read a passage from the book.",
303: "There is a farm on a large piece of land.",
304: "A sale started at the department store.",
305: "I joined a world tour.",
306: "I followed the road sign.",
307: "My exam grades have gone up.",
308: "I live in an apartment near the station.",
309: "I wrote a beautiful poem.",
310: "I received a wonderful gift on my birthday.",
311: "I made furniture from wood.",
312: "I consulted with the university professor.",
313: "I watched a movie by my favorite actor.",
314: "I received the electricity bill.",
315: "I wrote my address clearly.",
316: "I filled in the application form.",
317: "I was chosen as the student council president.",
318: "I met the store owner.",
319: "I bought vegetables at the local market.",
320: "I visited a beautiful island.",
321: "Let's have a balanced meal.",
322: "A large crowd gathered in front of the station.",
323: "I took a flight to Tokyo.",
324: "I went shopping at the mall.",
325: "Observing insects is my hobby.",
326: "I took a walk through a beautiful forest.",
327: "I brought a water bottle.",
328: "The noise from construction is loud.",
329: "I had lunch on the grass.",
330: "I like chocolate-flavored ice cream.",
331: "I wear clothes suitable for the season.",
332: "I get along well with my neighbor.",
333: "I have a dream about space.",
334: "I worked using a convenient tool.",
335: "Let's eat vegetables every day.",
336: "A police officer showed me the way.",
337: "I am doing research in the science department.",
338: "I ate cake after dinner.",
339: "I bought groceries at the supermarket.",
340: "A large truck is driving on the road.",
341: "I came up with a good idea.",
342: "Let's make sure to check the facts.",
343: "If a problem comes up, let's talk about it.",
344: "Walk on the right side of the road.",
345: "I will explain the details later.",
346: "I play a musical instrument called the piano.",
347: "The wheel of my bicycle broke.",
348: "I had lunch with my co-worker.",
349: "What type of music do you like?",
350: "It is a facility in the center of the city.",
351: "I put up with the boring class.",
352: "Please give a concrete example.",
353: "We need a creative solution.",
354: "Let's be curious about things we don't know.",
355: "Homemade cooking is very delicious.",
356: "Let's start with elementary English.",
357: "You need general knowledge.",
358: "Let's respect individual opinions.",
359: "Mental health is also important.",
360: "I was impressed by the novel idea.",
361: "I am good at a particular subject.",
362: "The design of the clothes is cute.",
363: "I aim to be a professional athlete.",
364: "The price was reasonable and helpful.",
365: "There was a remarkable discovery.",
366: "You need scientific evidence.",
367: "A significant change occurred.",
368: "Let's make a specific plan.",
369: "A technical problem occurred.",
370: "She is a suitable person for this job.",
371: "I built a house on flat land.",
372: "The road is wide.",
373: "A dish made with local ingredients.",
374: "Social media is a social tool.",
375: "Let's choose natural foods.",
376: "I completely understood.",
377: "I called directly.",
378: "My English is gradually improving.",
379: "I mostly speak in English.",
380: "Let's do it in the proper way.",
381: "Let's exercise regularly.",
382: "I was slightly late.",
383: "It suddenly started raining.",
384: "I haven't finished my homework yet.",
385: "There was once a castle here.",
386: "I carefully thought about the plan.",
387: "I usually commute by train.",
388: "I have already finished my homework.",
389: "It is still raining.",
390: "I like not only English but also math.",
391: "Let's try again.",
392: "However, I didn't give up.",
393: "Indeed, he is right.",
394: "Hurry up, otherwise you'll be late.",
395: "Perhaps it will rain.",
396: "I'm quite tired.",
397: "I'd rather walk.",
398: "You just need to practice.",
399: "Thank you truly.",
400: "This opinion is widely known.",
}

with open('words/grade-pre2.json') as f:
    data = json.load(f)

for w in data['words']:
    wid = w['id']
    if wid in EE:
        w['ee'] = EE[wid]

with open('words/grade-pre2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done! Checking first 3 words:")
for w in data['words'][:3]:
    print(json.dumps(w, ensure_ascii=False))
